services:
  - type: web
    name: phv-render-backend
    runtime: docker
    plan: free
    dockerfilePath: ./deploy/render/Dockerfile
    envVars:
      - key: APP_NAME
        value: HPV Hospital Console
      - key: HOSPITAL_NAME
        value: Nyeri Town Health Center
      - key: CLINIC_SITE_NAME
        value: Nyeri Town Health Center
      - key: WIPE_DATA_PASSWORD
        value: Adminpass
